sudo: required
dist: trusty

language: cpp

compiler:
 - clang
 - gcc

env:
  matrix:
    - CONF=release ARCH=x86_64

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libevent-dev liblog4cxx10-dev libcppunit-dev

install:

before_script:

script:
  - ./make.sh

after_success:
